In [ ]:
import yfinance as yf
import pandas as pd
import gspread as gs

In [ ]:
ticker = yf.Ticker("ABBV")
income_stmt = ticker.income_stmt
income_stmt.iat[16,0]
print(income_stmt.iat[16,3])
income_stmt
# 2023 15744231000.0
# 2020 17352119000.0

11363000000.0

,2023-12-31,2022-12-31,2021-12-31,2020-12-31,2019-12-31
Tax Effect Of Unusual Items,-203280000.0,-102245000.0,-130425000.0,-390690000.0,NaN
Tax Rate For Calcs,0.22,0.121,0.111,0.27,NaN
Normalized EBITDA,18096000000.0,25019000000.0,25108000000.0,13770000000.0,NaN
Total Unusual Items,-924000000.0,-845000000.0,-1175000000.0,-1447000000.0,NaN
Total Unusual Items Excluding Goodwill,-924000000.0,-845000000.0,-1175000000.0,-1447000000.0,NaN
Net Income From Continuing Operation Net Minority Interest,4863000000.0,11836000000.0,11542000000.0,4616000000.0,NaN
Reconciled Depreciation,8698000000.0,8467000000.0,8521000000.0,6471000000.0,NaN
Reconciled Cost Of Revenue,20415000000.0,17414000000.0,17446000000.0,15387000000.0,NaN
EBITDA,17172000000.0,24174000000.0,23933000000.0,12323000000.0,NaN
EBIT,8474000000.0,15707000000.0,15412000000.0,5852000000.0,NaN
Net Interest Income,-1684000000.0,-2044000000.0,-2384000000.0,-2280000000.0,NaN
Interest Expense,2224000000.0,2230000000.0,2423000000.0,2454000000.0,NaN
Interest Income,540000000.0,186000000.0,39000000.0,174000000.0,NaN
Normalized Income,5583720000.0,12578755000.0,12586575000.0,5672310000.0,NaN
Net Income From Continuing And Discontinued Operation,4863000000.0,11836000000.0,11542000000.0,4616000000.0,NaN
Total Expenses,40783000000.0,39240000000.0,37149000000.0,33065000000.0,NaN
Total Operating Income As Reported,12757000000.0,18117000000.0,17924000000.0,11363000000.0,NaN
Diluted Average Shares,1773000000.0,1778000000.0,1777000000.0,1765132819.0,NaN
Basic Average Shares,1765940733.0,1769181294.0,1768337696.0,1765132819.0,NaN
Diluted EPS,2.72,6.63,6.45,2.615101,NaN
Basic EPS,2.753773,6.6901,6.527034,2.615101,NaN
Diluted NI Availto Com Stockholders,4820000000.0,11782000000.0,11468000000.0,4556000000.0,NaN
Net Income Common Stockholders,4820000000.0,11782000000.0,11468000000.0,4556000000.0,NaN
Otherunder Preferred Stock Dividend,43000000.0,54000000.0,74000000.0,60000000.0,NaN
Net Income,4863000000.0,11836000000.0,11542000000.0,4616000000.0,NaN
Minority Interests,-10000000.0,-9000000.0,-7000000.0,-6000000.0,NaN
Net Income Including Noncontrolling Interests,4873000000.0,11845000000.0,11549000000.0,4622000000.0,NaN
Net Income Continuous Operations,4873000000.0,11845000000.0,11549000000.0,4622000000.0,NaN
Tax Provision,1377000000.0,1632000000.0,1440000000.0,-1224000000.0,NaN
Pretax Income,6250000000.0,13477000000.0,12989000000.0,3398000000.0,NaN
Other Income Expense,-5601000000.0,-3293000000.0,-3675000000.0,-7061000000.0,NaN
Other Non Operating Income Expenses,-4677000000.0,-2448000000.0,-2500000000.0,-5614000000.0,NaN
Special Income Charges,-778000000.0,-697000000.0,-1124000000.0,-1376000000.0,NaN
Other Special Charges,778000000.0,697000000.0,1124000000.0,1376000000.0,NaN
Gain On Sale Of Security,-146000000.0,-148000000.0,-51000000.0,-71000000.0,NaN
Net Non Operating Interest Income Expense,-1684000000.0,-2044000000.0,-2384000000.0,-2280000000.0,NaN
Interest Expense Non Operating,2224000000.0,2230000000.0,2423000000.0,2454000000.0,NaN
Interest Income Non Operating,540000000.0,186000000.0,39000000.0,174000000.0,NaN
Operating Income,13535000000.0,18814000000.0,19048000000.0,12739000000.0,NaN
Operating Expense,20368000000.0,21826000000.0,19703000000.0,17678000000.0,NaN
Other Operating Expenses,-179000000.0,56000000.0,432000000.0,NaN,-890000000.0
Research And Development,7675000000.0,6510000000.0,6922000000.0,6379000000.0,NaN
Selling General And Administration,12872000000.0,15260000000.0,12349000000.0,11299000000.0,NaN
Gross Profit,33903000000.0,40640000000.0,38751000000.0,30417000000.0,NaN
Cost Of Revenue,20415000000.0,17414000000.0,17446000000.0,15387000000.0,NaN
Total Revenue,54318000000.0,58054000000.0,56197000000.0,45804000000.0,NaN
Operating Revenue,54318000000.0,58054000000.0,56197000000.0,45804000000.0,NaN

In [ ]:
ticker.info.get('bookValue', 0)

4.535

In [ ]:
try:
  # 4 year shares
  shares_past = income_stmt.iat[16,3] if shares_past is not None else 0
  shares_current = income_stmt.iat[16,0] if income_stmt is not None else 0
  cagr_shares = shares_current/shares_past if shares_past != 0 else 0
except Exception:
  cagr_shares = 0
print(cagr_shares)

0

In [ ]:
def calculate_financial_metrics(ticker_symbol):
    # Initialize the Ticker object
    ticker = yf.Ticker(ticker_symbol)

    try:
        # Income Statement
        income_stmt = ticker.income_stmt
    except Exception:
        income_stmt = None

    try:
        # Sales
        sales = income_stmt.iat[-1, 0] if income_stmt is not None else 0
    except Exception:
        sales = 0

    try:
        # Net income
        net_income = income_stmt.iat[21, 0] if income_stmt is not None else 0
    except Exception:
        net_income = 0

    try:
        # % Sales
        percentage_sales = (net_income / sales) * 100 if sales != 0 else 0
    except Exception:
        percentage_sales = 0

    try:
        # Market Cap
        market_cap = ticker.info.get('marketCap', 0)
    except Exception:
        market_cap = 0

    try:
        # P/E
        pe_ratio = ticker.info.get('trailingPE', 0)
    except Exception:
        pe_ratio = 0

    try:
        # P/Book
        price_to_book = ticker.info.get('priceToBook', 0)
    except Exception:
        price_to_book = 0

    try:
        # P/Sales
        price_to_sales = ticker.info.get('priceToSalesTrailing12Months', 0)
    except Exception:
        price_to_sales = 0

    try:
        # Cash
        cash = ticker.info.get('totalCash', 0)
    except Exception:
        cash = 0

    try:
        # Debt
        total_debt = ticker.info.get('totalDebt', 0)
    except Exception:
        total_debt = 0

    try:
        # Net Cash
        net_cash = cash - total_debt if cash != 0 and total_debt != 0 else 0
    except Exception:
        net_cash = 0

    try:
        # Cash yield
        cash_yield = net_cash / market_cap if market_cap != 0 else 0
    except Exception:
        cash_yield = 0

    try:
        # CAGR Sales
        end_revenue = sales
        start_revenue = income_stmt.iat[-1, 3] if income_stmt is not None else 0
        cagr_sales = end_revenue/start_revenue if start_revenue != 0 else 0
    except Exception:
        cagr_sales = 0

    try:
        # ROE
        roe = ticker.info.get('returnOnEquity', 0)
    except Exception:
        roe = 0

    try:
        # Book tangible
        book_tangible = ticker.info.get('bookValue', 0)
    except Exception:
        book_tangible = 0

    try:
      # 4 year shares
      shares_past = income_stmt.iat[16,3] #if shares_past is not None else 0
      shares_current = income_stmt.iat[16,0] #if income_stmt is not None else 0
      cagr_shares = shares_current/shares_past*100 #if shares_past != 0 else 0
    except Exception:
      cagr_shares = 0

    try:
      # Net income CAGR 4 years
      start_income = income_stmt.iat[21, 3] if income_stmt is not None else 0
      cagr_net_income = net_income/start_income if start_income != 0 else 0
    except Exception:
      cagr_net_income = 0

    # Create dictionary with calculated metrics
    data = {
        'Ticker': ticker_symbol,
        'Sales': sales,
        'Net Income': net_income,
        '% Sales': percentage_sales,
        'Market Cap': market_cap,
        'P/E': pe_ratio,
        'P/Book': price_to_book,
        'P/Sales': price_to_sales,
        'Cash': cash,
        'Debt': total_debt,
        'Net Cash': net_cash,
        'Cash Yield': cash_yield,
        'CAGR Sales': cagr_sales,
        'ROE': roe,
        'Book Tangible': book_tangible,
        'CAGR Net Income (4 years)': cagr_net_income,
        'CAGR Shares (4 years)': cagr_shares
    }


    return data

In [ ]:
metrics = calculate_financial_metrics("AAPL")
metrics

{'Ticker': 'AAPL',
 'Sales': 383285000000.0,
 'Net Income': 96995000000.0,
 '% Sales': 25.30623426432028,
 'Market Cap': 3122542149632,
 'P/E': 31.259512,
 'P/Book': 46.86787,
 'P/Sales': 8.0978155,
 'Cash': 61801000960,
 'Debt': 101304000512,
 'Net Cash': -39502999552,
 'Cash Yield': -0.012650909950616851,
 'CAGR Sales': 1.3962260714350765,
 'ROE': 1.60583,
 'Book Tangible': 4.382,
 'CAGR Net Income (4 years)': 1.689484593544791,
 'CAGR Shares (4 years)': 90.73376571472338}

In [ ]:
import requests
from bs4 import BeautifulSoup

res = requests.get("https://en.wikipedia.org/wiki/List_of_S%26P_500_companies")
soup = BeautifulSoup(res.content,'lxml')
table = soup.find_all('table')[0]
df = pd.read_html(str(table))

symbols = [company["Symbol"] for company in df]


tickers = []

for i in range(len(symbols[0])):
  if type(symbols[0][i]) == str:
    tickers.append(symbols[0][i])

<ipython-input-7-386606bda476>:7: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))

In [ ]:
data = []

for ticker in tickers:
  metrics = calculate_financial_metrics(ticker)
  data.append(metrics)

def create_financial_metrics_dataframe(data, tickers):
  print(len(tickers))
  # Create DataFrame from data dictionary
  df = pd.DataFrame(data)
  return df

df = create_financial_metrics_dataframe(data, tickers)
df.fillna(0, inplace=True)

503

In [ ]:
df

,Ticker,Sales,Net Income,% Sales,Market Cap,P/E,P/Book,P/Sales,Cash,Debt,Net Cash,Cash Yield,CAGR Sales,ROE,Book Tangible,CAGR Net Income (4 years),CAGR Shares (4 years)
0,MMM,3.268100e+10,-6.995000e+09,-21.403874,68757143552,48.700394,17.558924,2.108209,10337999872,13790999552,-3452999680,-0.050220,1.015442,0.24314,7.128,-1.283722,-127.468231
1,AOS,3.852800e+09,5.566000e+08,14.446636,12085444608,21.412146,6.322194,3.076194,233300000,165100000,68200000,0.005643,1.330708,0.30342,13.107,1.613801,92.695124
2,ABT,4.010900e+10,5.723000e+09,14.268618,191771787264,34.769714,4.877423,4.708945,7218999808,14844999680,-7625999872,-0.039766,1.158952,0.14441,22.598,1.273192,120.925891
3,ABBV,5.431800e+10,4.820000e+09,8.873670,329926311936,62.486626,41.198460,5.998661,18069000192,74358996992,-56289996800,-0.170614,1.185879,0.00000,4.535,1.057946,112.267887
4,ACN,6.411174e+10,6.878761e+09,10.729330,200502394880,29.312729,7.229538,3.109729,5542094848,4601543168,940551680,0.004691,1.446335,0.26000,44.276,1.345041,135.252848
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,XYL,7.364000e+09,6.090000e+08,8.269962,31136452608,39.564816,3.011063,3.708486,815000000,2104000000,-1289000000,-0.041398,1.510254,0.07553,42.573,2.397638,177.656676
499,YUM,7.076000e+09,1.597000e+09,22.569248,38487830528,24.230497,0.000000,5.475577,680000000,11936000000,-11256000000,-0.292456,1.251946,0.00000,-27.601,1.766593,92.833876
500,ZBRA,4.584000e+09,2.960000e+08,6.457243,16610694144,72.367420,5.052402,3.812415,411000000,2355000064,-1944000064,-0.117033,1.030576,0.07326,63.739,0.587302,73.886329
501,ZBH,7.394200e+09,1.024000e+09,13.848692,22615678976,23.845985,1.794922,3.034684,393000000,6003800064,-5610800064,-0.248093,1.206724,0.07795,61.245,-7.372210,101.304348
502,ZTS,8.544000e+09,2.344000e+09,27.434457,85413863424,36.067436,16.911194,9.779467,1975000064,6800000000,-4824999936,-0.056490,1.280000,0.50047,11.069,1.431013,96.594013

In [ ]:
def rank_metrics(df):
    # Ensure the DataFrame contains the 'Ticker' column
    if 'Ticker' not in df.columns:
        raise ValueError("The DataFrame must contain a 'Ticker' column.")

    # Select only the specified columns for ranking
    columns_to_rank = ['% Sales', 'P/E', 'Cash Yield', 'P/Book', 'CAGR Sales', 'ROE', 'CAGR Net Income (4 years)']

    # Convert specified columns to numeric, coercing errors to NaN
    df[columns_to_rank] = df[columns_to_rank].apply(pd.to_numeric, errors='coerce')

    # Replace NaN values with 0
    df[columns_to_rank] = df[columns_to_rank].fillna(0)

    # Initialize a DataFrame to hold the rankings
    ranked_df = pd.DataFrame(index=df.index)

    # Rank P/E and P/B in descending order (lower value gets higher rank)
    ranked_df['Rank P/E'] = df['P/E'].rank(method='min', ascending=False)
    ranked_df['Rank P/Book'] = df['P/Book'].rank(method='min', ascending=False)

    # Rank the other columns in ascending order (higher value gets higher rank)
    for col in ['% Sales', 'Cash Yield', 'CAGR Sales', 'ROE', 'CAGR Net Income (4 years)']:
        ranked_df[f'Rank {col}'] = df[col].rank(method='min', ascending=True)

    # Set rank to 1 for any zero values
    for col in columns_to_rank:
        ranked_df[f'Rank {col}'][df[col] == 0] = 1

    # Calculate the total rank by summing the ranks
    ranked_df['Total Rank'] = ranked_df.sum(axis=1)

    # Add the Ticker column to the ranked DataFrame
    ranked_df['Ticker'] = df['Ticker']

    # Reorder the columns to have Ticker first
    final_columns = ['Ticker'] + [f'Rank {col}' for col in columns_to_rank] + ['Total Rank']
    ranked_df = ranked_df[final_columns]

    return ranked_df

ranked_df = rank_metrics(df)
ranked_df

,Ticker,Rank % Sales,Rank P/E,Rank Cash Yield,Rank P/Book,Rank CAGR Sales,Rank ROE,Rank CAGR Net Income (4 years),Total Rank
0,MMM,9.0,63.0,360.0,34.0,43.0,357.0,35.0,901.0
1,AOS,318.0,274.0,428.0,135.0,265.0,393.0,349.0,2162.0
2,ABT,316.0,130.0,375.0,175.0,124.0,252.0,271.0,1643.0
3,ABBV,211.0,37.0,230.0,14.0,151.0,1.0,218.0,862.0
4,ACN,247.0,175.0,426.0,113.0,342.0,366.0,291.0,1960.0
...,...,...,...,...,...,...,...,...,...
498,XYL,203.0,103.0,371.0,256.0,365.0,130.0,431.0,1859.0
499,YUM,411.0,240.0,140.0,1.0,209.0,1.0,383.0,1385.0
500,ZBRA,179.0,30.0,279.0,167.0,49.0,125.0,148.0,977.0
501,ZBH,307.0,243.0,169.0,370.0,175.0,135.0,12.0,1411.0
502,ZTS,444.0,119.0,350.0,38.0,224.0,457.0,308.0,1940.0

In [ ]:
ranked_df_ordered = ranked_df.sort_values(by='Total Rank', ascending=False)
ranked_df_ordered

,Ticker,Rank % Sales,Rank P/E,Rank Cash Yield,Rank P/Book,Rank CAGR Sales,Rank ROE,Rank CAGR Net Income (4 years),Total Rank
109,CINF,502.0,454.0,410.0,403.0,458.0,296.0,329.0,2852.0
42,ACGL,493.0,463.0,446.0,363.0,236.0,397.0,452.0,2850.0
269,JPM,501.0,429.0,498.0,372.0,296.0,279.0,370.0,2745.0
133,CTRA,448.0,388.0,304.0,424.0,497.0,193.0,489.0,2743.0
181,EG,499.0,466.0,462.0,440.0,22.0,354.0,464.0,2707.0
...,...,...,...,...,...,...,...,...,...
412,STX,155.0,42.0,183.0,1.0,11.0,1.0,131.0,524.0
69,BA,18.0,1.0,97.0,1.0,271.0,1.0,127.0,516.0
226,HAS,6.0,1.0,128.0,103.0,26.0,1.0,14.0,279.0
62,BRK.B,1.0,1.0,1.0,1.0,1.0,1.0,1.0,7.0
77,BF.B,1.0,1.0,1.0,1.0,1.0,1.0,1.0,7.0

In [ ]:
# Scrip para escribir en el sheet

from google.colab import auth
from google.auth import default

try:
  import gspread
except ModuleNotFoundError:
  if 'google.colab' in str(get_ipython()):
    %pip install gspread
  import gspread

In [ ]:
auth.authenticate_user()
creds, _ = default()
gc = gspread.authorize(creds)

In [ ]:
worksheet1 = gc.open_by_url('https://docs.google.com/spreadsheets/d/1mzaK-Rj_4FJHi-MBroQGagBCQhN1EFsfhbP1f0io_0I/edit?gid=0#gid=0')

sheet1  = worksheet1.get_worksheet(0)
sheet2  = worksheet1.get_worksheet(1)
sheet3  = worksheet1.get_worksheet(2)

sheet1.update([df.columns.values.tolist()] + df.fillna(-1).values.tolist())
sheet2.update([ranked_df.columns.values.tolist()] + ranked_df.fillna(-1).values.tolist())
sheet3.update([ranked_df_ordered.columns.values.tolist()] + ranked_df_ordered.fillna(-1).values.tolist())

{'spreadsheetId': '1mzaK-Rj_4FJHi-MBroQGagBCQhN1EFsfhbP1f0io_0I',
 'updatedRange': "'Hoja 3'!A1:I504",
 'updatedRows': 504,
 'updatedColumns': 9,
 'updatedCells': 4536}